services:
  - type: web
    name: rotabus-api
    plan: free
    env: node
    region: ohio
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run prisma:migrate
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
